name: elcm

model_type: segmented_locationchoice

segmentation_col: naics

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters:
- general_type != 'Residential'
- building_type_id != 5
- building_type_id != 6

alts_predict_filters:
- general_type != 'Residential'
- building_type_id != 5
- building_type_id != 6

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 5000

default_config:
    model_expression: np.log1p(non_residential_rent) + np.log1p(stories) + sum_residential_units
        + ave_unit_sqft + ave_lot_sqft + ave_income + hhsize + jobs + poor - 1